'''

Created by Ruslan

example of how to read graph generated by graphbuilder

'''


import networkx as nx
import csv

fh = open("edgelist.txt", 'rb')
G=nx.read_edgelist(fh, create_using=nx.DiGraph())
fh.close()
print (G.edges(data = True))
